site_name: NovelKit
site_description: "A toolkit for downloading and processing novels."
site_author: "Saudade Z"
repo_name: "novelkit"
repo_url: "https://github.com/saudadez21/novelkit"
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.action.edit
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate

plugins:
  - search
  - tags
  - privacy:
      assets: false
      links_attr_map:
        target: _blank
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            show_root_full_path: false
            show_signature: true
            show_source: false
            separate_signature: true
            merge_init_into_class: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md

  - Reference:
    - API Examples: reference/api-examples.md
    - Infra:
      - Config Adapter: reference/infra/config_adapter.md
      - Sessions: reference/infra/sessions.md
      - Chapter Storage: reference/infra/chapter_storage.md
      - Cookies: reference/infra/cookies.md
    - Libs:
      - Filesystem: reference/libs/filesystem.md
    - Plugins:
      - Overview: reference/plugins/overview.md
      - Client: reference/plugins/client.md
      - Fetcher: reference/plugins/fetcher.md
      - Parser: reference/plugins/parser.md
      - Processor: reference/plugins/processor.md
      - Registry: reference/plugins/registry.md
      - UI: reference/plugins/ui.md
    - Schemas: reference/schemas.md

not_in_nav: |
  supported-sites/site-details/*

exclude_docs: |
  /data/
